# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FiveSenses' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FiveSenses 
  pod 'FSCalendar'
  pod 'Refreshable'
  pod 'Toaster'

  target 'FiveSensesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FiveSensesUITests' do
    # Pods for testing
  end

end
